# Generated by Django 4.2.6 on 2023-10-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='uniqueid',
            field=models.CharField(default='your_default_value_here', max_length=112),
        ),
    ]
