# Generated by Django 4.2.6 on 2023-10-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_userdetail_uniqueid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='is_active',
        ),
    ]
